#!/bin/bash

program=`basename $0`

GETOPT=getopt
platform=$(uname)
if [[ "$platform" == 'Darwin' ]]; then
  if brew ls gnu-getopt >/dev/null; then
    GETOPT=$(brew ls gnu-getopt | head -1)
  else
    echo 'Error: getopt on OSX does not parse arguments properly' >&2
    echo 'brew install gnu-getopt' >&2
    exit 1
  fi
fi
ARGS=$($GETOPT -o acih? -l "all,images,containers,help" -n "$program" -- "$@");

function usage() {
  cat <<EOT
Usage: $program
  --all (-a)
  --containers (-c)
  --images (-i)
  --help (-h|-?)
EOT
}

# Don't fail on error until after parsing
set -o errexit

# Replace args with parsed arguments
eval set -- "$ARGS";

while true; do
  case "$1" in
    -a|--all)
      shift;
      opt_containers=true
      opt_images=true
      ;;
    -c|--containers)
      shift;
      opt_containers=true
      ;;
    -i|--images)
      shift;
      opt_images=true
      ;;
    -h|-\?|--help)
      shift;
      usage
      exit 0
      ;;
    --)
      shift
      break
      ;;
    *)
      echo "Invalid argument $1"
      shift
      usage
      exit 1
      ;;
  esac
done

if [ -z "$opt_containers" ] && [ -z "$opt_images" ] ; then
  usage
  exit 1
fi

if [ -n "$opt_containers" ]; then
  echo 'Removing stopped containers'
  if ! docker rm -v $(docker ps -a -q); then
    echo 'Failed to remove running containers'
    docker ps -a
    exit 2
  fi
fi
if [ -n "$opt_images" ]; then
  echo 'Removing unused images'
  ids=$(docker images -q --filter "dangling=true")
  docker rmi $ids
fi
